### ISSUE TITLE
Less verbose errors with connection issues

### ISSUE THREAD

**Issue by tonnitommi** [robocorp/robocorp#265]
Even though I "think" I have a connection, sometimes seeing this:

! connect failed; reconnecting in 2.5 seconds
Traceback (most recent call last):
  File "websockets.legacy.client", line 598, in __aiter__
  File "websockets.legacy.client", line 629, in __aenter__
  File "websockets.legacy.client", line 647, in __await_impl_timeout__
  File "websockets.legacy.client", line 654, in __await_impl__
  File "websockets.legacy.client", line 325, in handshake
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 401
! connect failed again; retrying in 3 seconds
Traceback (most recent call last):
  File "websockets.legacy.client", line 598, in __aiter__
  File "websockets.legacy.client", line 629, in __aenter__
  File "websockets.legacy.client", line 647, in __await_impl_timeout__
  File "websockets.legacy.client", line 654, in __await_impl__
  File "websockets.legacy.client", line 325, in handshake
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 401
! connect failed again; retrying in 5 seconds
Traceback (most recent call last):
  File "websockets.legacy.client", line 598, in __aiter__
  File "websockets.legacy.client", line 629, in __aenter__
  File "websockets.legacy.client", line 647, in __await_impl_timeout__
  File "websockets.legacy.client", line 654, in __await_impl__
  File "websockets.legacy.client", line 325, in handshake
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 401
! connect failed again; retrying in 8 seconds
Traceback (most recent call last):
  File "websockets.legacy.client", line 598, in __aiter__
  File "websockets.legacy.client", line 629, in __aenter__
  File "websockets.legacy.client", line 647, in __await_impl_timeout__
  File "websockets.legacy.client", line 654, in __await_impl__
  File "websockets.legacy.client", line 325, in handshake
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 401

**Comment by fabioz** [comment]
Fixed in https://github.com/robocorp/robocorp/commit/f84a15b1081883a94163eded98f647e23a7fbbc6
