### ISSUE TITLE
Nested custom types should be supported in the action server

### ISSUE THREAD

**Issue by fabioz** [robocorp/robocorp#293]
```
class Address(BaseModel):
    city: Annotated[str, Field(description="The city part of the address")]

class User(BaseModel):
    name: Annotated[str, Field(description="User's name")]
    address: Annotated[Optional[Address], Field(description="The user's address, optional")]
```

Current error:

```
Traceback (most recent call last):
  File "runpy", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "runpy", line 86, in _run_code
    exec(code, run_globals)
  File "robocorp.action_server.__main__", line 8, in <module>
  File "robocorp.action_server.cli", line 369, in main
    retcode = _main_retcode(args, exit=exit)
  File "robocorp.action_server.cli", line 718, in _main_retcode
    start_server(
  File "robocorp.action_server._server", line 130, in start_server
    func, openapi_extra = _actions_run.generate_func_from_action(action)
  File "robocorp.action_server._actions_run", line 308, in generate_func_from_action
    input_validator = fastjsonschema.compile(input_schema_dict)
  File "fastjsonschema", line 210, in compile
....
  File "contextlib", line 135, in __enter__
    return next(self.gen)
  File "fastjsonschema.ref_resolver", line 142, in resolving
  File "fastjsonschema.ref_resolver", line 40, in resolve_path
fastjsonschema.exceptions.JsonSchemaDefinitionException: Unresolvable ref: $defs
```

**Comment by fabioz** [comment]
Fixed in https://github.com/robocorp/robocorp/commit/67e5968c07b05eee8e0d3b39796aa513b6ec65a8
