### ISSUE TITLE
Browser related actions fail

### ISSUE THREAD

**Issue by mikahanninen** [robocorp/robocorp#365]
### Target components

action_server, actions, browser

### What is wrong

Browser (robocorp-browser) related actions in my action package fail to run either when run from VSCode Robocorp extension or via Action Server.

The last call from the action being executed is `page = browser.goto(url)`

Code: https://github.com/robocorp/prebuilt-actions/tree/prebuilt-browsing

Full stacktrace:
```bash
========================= Running: get_website_content =========================
get_website_content status: FAIL

<class 'NotImplementedError'>
================= Full Traceback (running get_website_content) =================
Traceback (most recent call last):
  File "c:\ProgramData\robocorp\ht\31cb85e_b1f3c24_1c0bc041\lib\site-packages\robocorp\tasks\_commands.py", line 453, in run
    result = task.run(**kwargs)
  File "c:\ProgramData\robocorp\ht\31cb85e_b1f3c24_1c0bc041\lib\site-packages\robocorp\tasks\_task.py", line 57, in run
    return self.method(**kwargs)
  File "e:\koodi\repos\robocorp\prebuilt-actions\browsing\actions.py", line 88, in get_website_content
    page = browser.goto(url)
  File "c:\ProgramData\robocorp\ht\31cb85e_b1f3c24_1c0bc041\lib\site-packages\robocorp\browser\__init__.py", line 238, in goto
    p = page()
  File "c:\ProgramData\robocorp\ht\31cb85e_b1f3c24_1c0bc041\lib\site-packages\robocorp\browser\__init__.py", line 133, in page
    return _context.page()
  File "c:\ProgramData\robocorp\ht\31cb85e_b1f3c24_1c0bc041\lib\site-packages\robocorp\tasks\_lifecycle.py", line 32, in new_func
    cache.append(func(*args, **kwargs))
  File "c:\ProgramData\robocorp\ht\31cb85e_b1f3c24_1c0bc041\lib\site-packages\robocorp\browser\_context.py", line 260, in page
    ctx: BrowserContext = context()
  File "c:\ProgramData\robocorp\ht\31cb85e_b1f3c24_1c0bc041\lib\site-packages\robocorp\tasks\_lifecycle.py", line 19, in new_func
    cache.append(next(iter_in))
  File "c:\ProgramData\robocorp\ht\31cb85e_b1f3c24_1c0bc041\lib\site-packages\robocorp\browser\_context.py", line 225, in context
    ctx = browser().new_context(**all_kwargs)
  File "c:\ProgramData\robocorp\ht\31cb85e_b1f3c24_1c0bc041\lib\site-packages\robocorp\tasks\_lifecycle.py", line 19, in new_func
    cache.append(next(iter_in))
  File "c:\ProgramData\robocorp\ht\31cb85e_b1f3c24_1c0bc041\lib\site-packages\robocorp\browser\_context.py", line 179, in browser
    browser = __launch_browser_or_context(True, **kwargs)
  File "c:\ProgramData\robocorp\ht\31cb85e_b1f3c24_1c0bc041\lib\site-packages\robocorp\browser\_context.py", line 148, in __launch_browser_or_context
    launcher = _browser_launcher()
  File "c:\ProgramData\robocorp\ht\31cb85e_b1f3c24_1c0bc041\lib\site-packages\robocorp\tasks\_lifecycle.py", line 32, in new_func
    cache.append(func(*args, **kwargs))
  File "c:\ProgramData\robocorp\ht\31cb85e_b1f3c24_1c0bc041\lib\site-packages\robocorp\browser\_context.py", line 97, in _browser_launcher
    browser_type: BrowserType = _browser_type()
  File "c:\ProgramData\robocorp\ht\31cb85e_b1f3c24_1c0bc041\lib\site-packages\robocorp\tasks\_lifecycle.py", line 32, in new_func
    cache.append(func(*args, **kwargs))
  File "c:\ProgramData\robocorp\ht\31cb85e_b1f3c24_1c0bc041\lib\site-packages\robocorp\browser\_context.py", line 78, in _browser_type
    pw = playwright()
  File "c:\ProgramData\robocorp\ht\31cb85e_b1f3c24_1c0bc041\lib\site-packages\robocorp\tasks\_lifecycle.py", line 19, in new_func
    cache.append(next(iter_in))
  File "c:\ProgramData\robocorp\ht\31cb85e_b1f3c24_1c0bc041\lib\site-packages\robocorp\browser\_context.py", line 65, in playwright
    pw = sync_playwright().start()
  File "c:\ProgramData\robocorp\ht\31cb85e_b1f3c24_1c0bc041\lib\site-packages\playwright\sync_api\_context_manager.py", line 84, in start
    return self.__enter__()
  File "c:\ProgramData\robocorp\ht\31cb85e_b1f3c24_1c0bc041\lib\site-packages\playwright\sync_api\_context_manager.py", line 77, in __enter__
    dispatcher_fiber.switch()
  File "c:\ProgramData\robocorp\ht\31cb85e_b1f3c24_1c0bc041\lib\site-packages\playwright\sync_api\_context_manager.py", line 56, in greenlet_main
    self._loop.run_until_complete(self._connection.run_as_sync())
  File "c:\ProgramData\robocorp\ht\31cb85e_b1f3c24_1c0bc041\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "c:\ProgramData\robocorp\ht\31cb85e_b1f3c24_1c0bc041\lib\site-packages\playwright\_impl\_connection.py", line 263, in run_as_sync
    await self.run()
  File "c:\ProgramData\robocorp\ht\31cb85e_b1f3c24_1c0bc041\lib\site-packages\playwright\_impl\_connection.py", line 272, in run
    await self._transport.connect()
  File "c:\ProgramData\robocorp\ht\31cb85e_b1f3c24_1c0bc041\lib\site-packages\playwright\_impl\_transport.py", line 133, in connect
    raise exc
  File "c:\ProgramData\robocorp\ht\31cb85e_b1f3c24_1c0bc041\lib\site-packages\playwright\_impl\_transport.py", line 120, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "c:\ProgramData\robocorp\ht\31cb85e_b1f3c24_1c0bc041\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "c:\ProgramData\robocorp\ht\31cb85e_b1f3c24_1c0bc041\lib\asyncio\base_events.py", line 1681, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "c:\ProgramData\robocorp\ht\31cb85e_b1f3c24_1c0bc041\lib\asyncio\base_events.py", line 498, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

```

### System info

Failing at Windows 11.
Works at MacOS Sonoma 14.4.1

Both running latest VSCode + extensions.

### Example script

Action which fails (for example). `get_website_content`

**Comment by fabioz** [comment]
Closing (this was related to a library changing global asyncio settings).
