### ISSUE TITLE
`windows`: Generic improvements

### ISSUE THREAD

**Issue by cmin764** [robocorp/robocorp#98]
A few observations to tackle before releasing **v1**.

- Documentation:
  - Be specific about having the `timeout` in seconds under the docstrings
  - Fix `calc = find_window("name:Calculator")` into `calc = windows.find_window("name:Calculator")` in the main docs
  - API docs: not all the arguments are formatted properly as a bullet list (maybe due to inconsistent spacing, like leading EOL)
- Behaviour:
  - List user only processes (when matching a window based on PID) for speed gain
  - `windows.find()` might be too verbose in the terminal output (even printing the element tree multiple times when there are no matches) -> can be configured to be less verbose
  - Fix unicode error post-run during console message write (see trace below) -> encoding issue to be solved in `tasks` (might be fixed by setting UTF-8 as encoding through env var)
  - Searching (most probably wrongly) for a control with `Desktop().find()` will lead into a lot of trace console output (until the timeout depletes) compared to the recommended pattern of `windows.find_window().find()` -> bad usage pattern
- Functionality:
  - A locator like `'name:"Page setup" type:WindowControl'` doesn't find the "Notepad" > "Page setup" window with `windows.find_window()` but it works with `RPA.Windows.control_window()` (example below) -> designed like this on purpose for better & faster experience
  - `.find()` and `.find_window()` fails and raises when something isn't found, what about logging a warning and returning `None` if a parameter like `strict=False` is set explicitly? (so we don't need to guard with try-except every time we test the existence of a control/window)

Test [Task Package](https://github.com/cmin764/robots/tree/main/kari-notepad)

----

<img width="999" alt="Screenshot 2023-12-06 at 1 42 59 PM" src="https://github.com/robocorp/robo/assets/709053/bcb4506c-f739-49a3-8605-feb7aa6f4b32">

```
Error calling: <bound method Context._after_task_run of <robocorp.tasks._task.Context object at 0x000001E754521D80>>.
Traceback (most recent call last):
  File "C:\ProgramData\robocorp\ht\b395beb_b1f3c24_9ba66f27\lib\site-packages\robocorp\tasks\_callback.py", line 48, in __call__
    c(*args, **kwargs)
  File "C:\ProgramData\robocorp\ht\b395beb_b1f3c24_9ba66f27\lib\site-packages\robocorp\tasks\_task.py", line 169, in _after_task_run
    show(f"{msg}", kind=status_kind)
  File "C:\ProgramData\robocorp\ht\b395beb_b1f3c24_9ba66f27\lib\site-packages\robocorp\tasks\_task.py", line 142, in show
    console_message(msg, kind, flush=flush)
  File "C:\ProgramData\robocorp\ht\b395beb_b1f3c24_9ba66f27\lib\site-packages\robocorp\log\__init__.py", line 374, in console_message
    stream.write(message)
  File "C:\ProgramData\robocorp\ht\b395beb_b1f3c24_9ba66f27\lib\site-packages\robocorp\log\redirect.py", line 114, in write
    self._original.write(s)
  File "C:\ProgramData\robocorp\ht\b395beb_b1f3c24_9ba66f27\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\ue711' in position 6207: character maps to <undefined>
```

```python
from RPA.Windows import Windows
from robocorp import windows
from robocorp.tasks import task

WIN = Windows()

@task
def notepad_automation():
    page_setup_locator = 'name:"Page setup" type:WindowControl'
    WIN.control_window(page_setup_locator)
    page_window = windows.find_window(page_setup_locator)
```

```
...
Thread 0x00003050 (most recent call first):
  File "C:\ProgramData\robocorp\ht\b395beb_b1f3c24_9ba66f27\lib\threading.py", line 320 in wait
  File "C:\ProgramData\robocorp\ht\b395beb_b1f3c24_9ba66f27\lib\queue.py", line 171 in get
  File "C:\ProgramData\robocorp\ht\b395beb_b1f3c24_9ba66f27\lib\site-packages\robocorp\tasks\_log_output_setup.py", line 73 in write_in_thread
  File "C:\ProgramData\robocorp\ht\b395beb_b1f3c24_9ba66f27\lib\threading.py", line 953 in run
  File "C:\ProgramData\robocorp\ht\b395beb_b1f3c24_9ba66f27\lib\threading.py", line 1016 in _bootstrap_inner 
  File "C:\ProgramData\robocorp\ht\b395beb_b1f3c24_9ba66f27\lib\threading.py", line 973 in _bootstrap        

Current thread 0x000018ac (most recent call first):
  File "C:\ProgramData\robocorp\ht\b395beb_b1f3c24_9ba66f27\lib\site-packages\robocorp\windows\_vendored\uiautomation\uiautomation.py", line 6350 in GetFirstChildControl
  File "C:\ProgramData\robocorp\ht\b395beb_b1f3c24_9ba66f27\lib\site-packages\robocorp\windows\_vendored\uiautomation\uiautomation.py", line 6403 in GetChildren
  File "C:\ProgramData\robocorp\ht\b395beb_b1f3c24_9ba66f27\lib\site-packages\robocorp\windows\_iter_tree.py", line 142 in iter_tree
  File "C:\ProgramData\robocorp\ht\b395beb_b1f3c24_9ba66f27\lib\site-packages\robocorp\windows\_control_element.py", line 582 in _iter_children_nodes
  File "C:\ProgramData\robocorp\ht\b395beb_b1f3c24_9ba66f27\lib\site-packages\robocorp\windows\_control_element.py", line 487 in find
  File "z:\Repos\robots\kari-notepad\tasks.py", line 34 in notepad_automation
  File "C:\ProgramData\robocorp\ht\b395beb_b1f3c24_9ba66f27\lib\site-packages\robocorp\tasks\_task.py", line 30 in run
  File "C:\ProgramData\robocorp\ht\b395beb_b1f3c24_9ba66f27\lib\site-packages\robocorp\tasks\_commands.py", line 367 in run
  File "C:\ProgramData\robocorp\ht\b395beb_b1f3c24_9ba66f27\lib\site-packages\robocorp\tasks\_argdispatch.py", line 20 in _dispatch
  File "C:\ProgramData\robocorp\ht\b395beb_b1f3c24_9ba66f27\lib\site-packages\robocorp\tasks\_argdispatch.py", line 167 in process_args
  File "C:\ProgramData\robocorp\ht\b395beb_b1f3c24_9ba66f27\lib\site-packages\robocorp\tasks\cli.py", line 41 in main
  File "C:\ProgramData\robocorp\ht\b395beb_b1f3c24_9ba66f27\lib\site-packages\robocorp\tasks\__main__.py", line 4 in <module>
  File "C:\ProgramData\robocorp\ht\b395beb_b1f3c24_9ba66f27\lib\runpy.py", line 86 in _run_code
  File "C:\ProgramData\robocorp\ht\b395beb_b1f3c24_9ba66f27\lib\runpy.py", line 196 in _run_module_as_main   
Windows fatal exception: code 0x80040155
...
```

**Comment by fabioz** [comment]
@cmin764 The verbose errors may be tweaked in the config already.

See: robocorp.windows._config.Config.disabled_verbose_errors

**Comment by cmin764** [comment]
> @cmin764 The verbose errors may be tweaked in the config already.
> 
> See: robocorp.windows._config.Config.disabled_verbose_errors

Do you think it would be better to have these disabled by default and enabling them on request?

**Comment by fabioz** [comment]
Well, initially it was like that, but I found myself wishing it was active when I made an error, which prompted the change (because then it gives you information to fix it), whereas the cases where I didn't want it were only those where I actually expected an error.

**Comment by cmin764** [comment]
Finding a window inside the main window with `.find()` will work instead:
```python
main_window = windows.find_window('control:WindowControl and class:Notepad')
page_window = main_window.find('"Page setup"')
page_window.send_keys("{Enter}")  # presses OK and closes the sub-window
```

**Comment by fabioz** [comment]
This is on purpose... the problem with the approach on RPA.Windows is that it wouldn't scope the initial window and thus could end up going very deep on the depth first approach on wrong windows before finding the actual top-level window of interest, so, we now force the user to find the top-level window first.

**Comment by cmin764** [comment]
The `charmap` encoding error can be reproduced simply with this code:

```python
    desktop.windows_run("notepad.exe")
    notepad_window = windows.find_window("control:WindowControl and class:Notepad")
    notepad_window.click("control:MenuItemControl and name:Invalid")
```

Note that `name:Invalid` which is placed like that on purpose, in order to not find something (place where `name:File` would have worked instead).

This leads into good logging in the log file but a [failure](https://gist.github.com/cmin764/d17ac09d65a762c2a523ad1995e7ff08) in the console output reporting this.

**Comment by cmin764** [comment]
Also, encountering kind of _duplicate_ error logs when printing a handled exception, is that expected?

Uncomment the `print` from [here](https://github.com/cmin764/robots/blob/main/kari-notepad/tasks.py#L42) to reproduce it.

<img width="1283" alt="Screenshot 2023-12-06 at 7 21 57 PM" src="https://github.com/robocorp/robo/assets/709053/679d5620-53f8-4ecb-bf77-7d1398903487">

**Comment by fabioz** [comment]
@cmin764 this is actually a classic python encoding issue.

Probably some window you have has some binary being returned which cannot be represented as `cp1252`.

We should probably encode first (in robocorp-log) to bytes with `replace` as alternate and write to sys.stdout.buffer instead of sys.stdout.

This warrants a test for dealing with unicode in robocorp-log...

For fixing it in your machine, you could try to set `PYTHONIOENCODING` to `utf-8` (considering that what you're printing can be represented in utf-8).

Anyways, the culprit here isn't robocorp-windows.

**Comment by cmin764** [comment]
@fabioz Do you see as good design to introduce a `strict=True` param to the finding functions so they won't raise when this is set to `False`? (to test the existence of an element/window)

**Comment by fabioz** [comment]
I think it's a nice to have...

`strict` seems like an ambiguous name in that context (it seems to imply strictness of the locator for me).


I think that it could be something as 
```
class RaiseError: pass
RAISE_ERROR = RaiseError() # Instance that acts as a sentinel to be identity-checked.

default=RAISE_ERROR
```
where the user can change to `default=None` would be better or actually name it 'raise_error' (true by default).

**Comment by kariharju** [comment]
I would not add this use case as a parameter to find
I think just having a clearly separate .exists() that returns a boolean would make the resulting code more readable and serve the use case.
So the use case stems from "detect in which state the app is" doing this by detecting is a specific element is present or not, and just having direct if-else paths etc.

**Comment by fabioz** [comment]
I don't like the `exists` in this case because finding a window is slow, so, if the user does an `exists` to then find the window that's too much time spent. 

Also, code as:

```
window = windows.find(..., default=None)
if window is not None:
    ...
```

Is basically the same as:

```
exists = windows.exists(...)
if exists:
    ...
```

But the user has to do a 2nd query to get the window of interest afterwards.

Also, remember that there's a timeout on all the find apis, so, we handle the `wait_for_element` case by default in the find APIs.

**Comment by kariharju** [comment]
OK, I did not understand the comment around the default in the previous messages.
This solves the use case better.

**Comment by cmin764** [comment]
@fabioz We should pay attention on how we write the params description on the docstring, as any empty line break in between the argument description will break the bullet-point formatting. ([example](https://github.com/robocorp/robo/blob/master/windows/docs/api/robocorp.windows.md#method-find_window))

Going to fix this everywhere `timeout` is specified and in general in all the `find[_...]` functions/methods.

**Comment by fabioz** [comment]
Ok... as a note, we could also fix our lazydocs fork to improve that.
